class SolarPanel:
    def __init__(self, efficiency, area):
        """
        Initialize a SolarPanel object.

        Parameters:
        - efficiency: Float. The efficiency of the solar panel (0-1).
        - area: Float. The area of the solar panel in square meters (m^2).
        """
        self.efficiency = efficiency
        self.area = area

    def generate_power(self, sunlight_intensity):
        """
        Calculate power generation of the solar panel.

        Parameters:
        - sunlight_intensity: Float. The intensity of sunlight (kW/m^2).

        Returns:
        - Power generated by the solar panel in kW.
        """
        return sunlight_intensity * self.efficiency * self.area
